-- Futmondo Insights - Phase 1 Intelligence Schema (v3)
-- Execute this in the Supabase SQL Editor to create the intelligence-layer tables.

-- ============================================================
-- Table 1: player_daily_snapshots
-- ============================================================
-- Daily snapshots of player valuation, stats, and ownership for
-- trend analysis, charting, and historical regression.

CREATE TABLE IF NOT EXISTS player_daily_snapshots (
    id BIGSERIAL PRIMARY KEY,
    player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
    championship_id TEXT REFERENCES championships(id) ON DELETE CASCADE,
    value BIGINT NOT NULL,
    daily_change BIGINT DEFAULT 0,
    points INTEGER DEFAULT 0,
    fis_score NUMERIC(5,2),
    status TEXT DEFAULT 'ok',
    owner_team_id TEXT REFERENCES user_teams(id) ON DELETE SET NULL,
    is_on_market BOOLEAN DEFAULT FALSE,
    clause_price BIGINT,
    snapshot_date DATE DEFAULT CURRENT_DATE,
    recorded_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(player_id, championship_id, snapshot_date)
);

-- Indices for player_daily_snapshots
CREATE INDEX IF NOT EXISTS idx_snapshots_player ON player_daily_snapshots(player_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_championship ON player_daily_snapshots(championship_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_owner ON player_daily_snapshots(owner_team_id, snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_market ON player_daily_snapshots(is_on_market, snapshot_date DESC);

-- ============================================================
-- Table 2: manager_dna_profiles
-- ============================================================
-- Computed profiles of each manager's trading behavior, used for
-- predictive analytics and personalized recommendations.

CREATE TABLE IF NOT EXISTS manager_dna_profiles (
    team_id TEXT PRIMARY KEY REFERENCES user_teams(id) ON DELETE CASCADE,
    championship_id TEXT REFERENCES championships(id) ON DELETE CASCADE,
    aggressiveness NUMERIC(5,2) DEFAULT 50.0,
    avg_overpayment_pct NUMERIC(5,2) DEFAULT 0.0,
    fav_position TEXT,
    trading_frequency NUMERIC(5,2) DEFAULT 0.0,
    avg_holding_days NUMERIC(5,2) DEFAULT 0.0,
    total_trades INTEGER DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for manager_dna_profiles
CREATE INDEX IF NOT EXISTS idx_manager_dna_championship ON manager_dna_profiles(championship_id);
CREATE INDEX IF NOT EXISTS idx_manager_dna_aggressiveness ON manager_dna_profiles(aggressiveness);

-- ============================================================
-- Table 3: decision_log
-- ============================================================
-- Audit trail of AI recommendations, user actions, and realized
-- outcomes for model training and ROI tracking.

CREATE TABLE IF NOT EXISTS decision_log (
    id BIGSERIAL PRIMARY KEY,
    championship_id TEXT REFERENCES championships(id) ON DELETE CASCADE,
    user_team_id TEXT REFERENCES user_teams(id) ON DELETE CASCADE,
    player_id TEXT REFERENCES players(id) ON DELETE CASCADE,
    recommendation_type TEXT NOT NULL,
    recommended_value NUMERIC,
    actual_action_taken TEXT,
    confidence_pct NUMERIC(5,2),
    outcome_roi NUMERIC(5,2),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for decision_log
CREATE INDEX IF NOT EXISTS idx_decision_log_team ON decision_log(user_team_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_decision_log_championship ON decision_log(championship_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_decision_log_player ON decision_log(player_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_decision_log_type ON decision_log(recommendation_type);

-- ============================================================
-- Table 4: user_smart_alerts
-- ============================================================
-- Personalized push notifications generated by the intelligence
-- engine for each user team.

CREATE TABLE IF NOT EXISTS user_smart_alerts (
    id BIGSERIAL PRIMARY KEY,
    user_team_id TEXT REFERENCES user_teams(id) ON DELETE CASCADE,
    championship_id TEXT REFERENCES championships(id) ON DELETE CASCADE,
    alert_type TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    severity TEXT DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices for user_smart_alerts
CREATE INDEX IF NOT EXISTS idx_alerts_team ON user_smart_alerts(user_team_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_unread ON user_smart_alerts(user_team_id, is_read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_championship ON user_smart_alerts(championship_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_type ON user_smart_alerts(alert_type);